### ISSUE TITLE
コメントの匿名化機能

### ISSUE THREAD

**Issue by Compeito** [Compeito/tsukuriga#12]
* 閲覧者が任意でコメントを匿名に出来る
  * 気軽に助言、批判等出来る
  * 馴れ合い対策
* 投稿者側で匿名コメントを拒否できる(デフォルトは許可)
* 投稿者側は拒否設定時に匿名コメントを開示できる

紛争の元になりかねない機能なのでなるべく分かりやすいガイドラインが必要と思われる

**Comment by Hayakuchi0** [comment]
とりあえず上記記載の機能を全て実装したプルリクエスト #19 を作成しました
ご確認いただければ幸いです
あと2点ちょっと聞きたいことがあるのでお答えいただければ幸いです
1. タスクの優先順位について、Projectsに埋まってるタスクを先にやったほうがいいでしょうか？それともissueに上がってる方のタスクを先に処理したほうがいいでしょうか？
2. 匿名コメントについてのガイドラインについては以下で大丈夫でしょうかね？
馴れ合いについてはユーザーの楽しみのひとつではありますし匿名化しても効果が薄いのでDiscordに誘導するほうが良さそうな気がしますので省きましたが…

```
# 匿名コメント機能について
ツクリガには投稿された動画に対し匿名でのコメントを行える機能を実装しました。

* 気軽に助言や批判を行うことができるようにするため
* (事前の警告は必須なものの)R18作品も視聴や投稿が可能なので、作品を見たことを内緒にしたいけど応援できるようにするため

などが主な理由です。
ただし、投稿した人物が誰かというデータはサーバー側で保存されています。
匿名だからといって嫌がらせ等の悪質な行為をする場合は速やかにアクセス規制をかける所存ですので、通常の利用規約通りにご利用ください。
また、動画投稿者は匿名コメントを拒否することができます。
既にコメントが投稿された動画の匿名コメントを拒否された場合、その動画に対して匿名コメントを送信することができなくなるだけでなく、既にその動画に投稿された匿名コメントの投稿者は全て開示されますのでご了承ください。
```

**Comment by Compeito** [comment]
1. issueに載せてる「機能追加」は元々Projectにあったものを移動させてメモ代わりにしてるだけで、優先度としては変わらないです
2. ありがとうございます。ガイドライン作成時に参考にさせていただきます

馴れ合い対策というのはあくまで身内同士で評価するだけの環境にならないようにと思ってのことでしたが、たしかに匿名にするだけだと効果が薄そうです
そもそもコメントの匿名化とだけ押し出すと「匿名化機能を利用するのは後ろめたい気持ちがあるから」という印象が強くなるので、匿名化の適用はそのままに、例えばチェックボックスの名前を「アドバイスコメントをする」とかにしても良さそうです

**Comment by Hayakuchi0** [comment]
1について承知しました
2については匿名化の名目を変えるほうが返って印象操作と思われそうですし、「誰が投稿したか内緒にする」くらいの表現のほうが無難な気がします
実際賛否両論な作品を見た際に内緒にしたい人もいるでしょうし…
特に匿名化機能で荒れたときにここを掘られたら「印象操作だ！」みたいな話が出てきて燃料になる可能性も十分あります
それだったら最初から危険性を周知した上で、悪用した人はBANすることを明記するほうが良い気がします
