### ISSUE TITLE
コメントに返信機能が欲しい

### ISSUE THREAD

**Issue by Hayakuchi0** [Compeito/tsukuriga#27]
コメントの返信機能が欲しいとの要望がありました
たしかに冷静に考えると作品のコメントへのお礼とかできると楽しそうですしあった方がいい気もします
https://mobile.twitter.com/_u3jo/status/1118402378657488896

**Comment by Compeito** [comment]
必要ですね。デザインとしてはYoutubeみたいにコメントへの返信がスレッドになってる感じが良いです

```python
parent = models.Foreignkey('self', verbose_name='親コメント', on_delete=models.CASCADE)
```
とするとモデル自身を外部キーに出来るらしいので、モデル作成時はこれで返信元を指定して、コメント一覧取得では逆引きでchildrenとしてjsonメソッドにフィールドを追加するとかが良いと思います

**Comment by Hayakuchi0** [comment]
実装について考えたんですが、Youtubeみたいにコメントへの返信をスレッド形式にするには以下の問題があるという結論になりました

・データがループ構造になりうるため対策のためにコードが肥大化するおそれがあること
・REST APIを弄る関係上影響範囲が拡大するおそれがあること
・Youtubeと比べてコメント欄が非常に狭いのでスレッド形式にする場合表示幅が狭くなる、またはTwitterのリプライ欄のような表示となりツリー構造がわかりづらい

そこで、Youtubeのようにツリー構造として構成するのではなく、ふたばや2chのようにコメントにIDをつけて、アンカーによって参照できる形にするほうが望ましいと思われます
これなら追加する必要があるのはコメント本体を表すページと、フロント側でそこへのリンクへと変換する作業だけで済みます
というわけで実装の際にはアンカー方式としたいのですが、いかがでしょうか？

**Comment by Compeito** [comment]
たしかに返信に返信できるとなるとコード的にもツリー表示的にも問題ありそうです。最低でもYoutubeに習って二層目移行は同じ列に表示するとか工夫が必要そうです

アンカー方式にするにしてもコメント単体用にURLを用意する必要はないと思います。例えばコメント下の「返信する」ボタンを押すと自動でコメント入力に「>>コメントID」が挿入されて、実際のコメントでは`href="#コメントID"`のページ内リンクに置換されてるとか
もっと言えば@usernameをリンクに置換するだけでも返信には一応なりそうです

**Comment by Hayakuchi0** [comment]
たしかに@usernameをリンクに置換するだけで返信になりそうですし、実装コストもバグも一番少なそうです
物足りないと思ったらそのリンクから動画につけられたユーザーごとのコメント一覧を表示するみたいに拡張することも可能ですし@usernameをリンクにしたアンカー方式に返信するボタン搭載の形がよさそうです
とりあえずその方式で明日の23時までに作ってプルリク送ってみますね
