### ISSUE TITLE
ランキング機能実装

### ISSUE THREAD

**Issue by Compeito** [Compeito/tsukuriga#34]
* 概ねAltwugと同じように作る
* まず作りやすいお気に入りリスト順から拡張性を考慮して実装
* 再生回数のみ日別にデータを取れないので実装を見直す必要がある

**Comment by Compeito** [comment]
4bde7a6083d245a4cba732c9a8bcde1ad61ce92c から d0eb9fab0cef002d32a9b943028d6f6b18018a3b で基礎部分実装完了

**Comment by Hayakuchi0** [comment]
まずはAltwug時代に有耶無耶になってしまった再生数を表すViewオブジェクトについて、素直に考えるならこんなオブジェクトを作って、ランキングの更新と同時に動画1つにつきひとつを毎日作成するみたいな形でどうでしょうか？
動画のviews_countプロパティについては全期間の累計として残し、Viewの作成と同時に前日のView分を追加という形で更新、動画の再生時にviews_countではなく当日のViewオブジェクトに1加算
Viewの保持期間は365日にして前日、週間、月間、年間の集計を可能とすれば丸く収まりそうな気がします(年間については個人的に欲しかったので…)
```
class View(models.Model):
    day = models.DateField("集計日",blank=False)
    views_count = models.PositiveIntegerField("当日再生回数",blank=False,default=0)
    video = models.ForeginField(upload.Video,verbos_name="動画",related_name="view_of_days")
```

データベースを圧迫するという問題が発生しそうな場合、Viewの保持期間を30日とし、月別の集計としてMonthViewを1動画あたり12個作るという少し複雑な構成にすれば1動画あたり閲覧数管理のデータが365個から42個に圧縮できて解決します

**Comment by Compeito** [comment]
年間ランキングは流石にいらないんじゃないでしょうか。というかデータベース圧迫も年間を作らなければだいぶ緩和しそうです
今現在星データは今日のものがあればそれに追加、無ければ新規作成して追加という実装になってるんですが、これとほぼ同じように実装するつもりです。Viewモデルもだいたいそんな感じになると思います

**Comment by Hayakuchi0** [comment]
最近のうちに新しい仕様できてたんですね…
了解です
ではコメント返信機能作ったあとにまだできてなければ以下のようにつくりますね
* Viewオブジェクトは上記におけるdayを削除したもの
* 閲覧数を増やす処理についてはcore/views.pyのwatch関数で、ajax/viewsのadd_pointと似たようなことをする
* Videoに入れてあるviews_countはviews_count_oldに名称変更、新しく読み取り専用プロパティとしてviews_countを追加(views_countは動画ごとのViewオブジェクトにおけるviews_count全て+Videoのviews_count_oldの合計を返す関数とする)
* ランキング更新時に30日以上経過したViewオブジェクトは削除、削除と同時にVideoのviews_count_oldに閲覧数を加算
