### ISSUE TITLE
ランキング機能実装(星順)

### ISSUE THREAD

**Issue by Compeito** [Compeito/tsukuriga#37]
#34

**Comment by Hayakuchi0** [comment]
(星順)って書いてありますけども、これは要するにAltwugの頃に実装してた「星の人気順」と同じ仕様という認識でいいんでしょうか？
とりあえず以前Altwugで実装した際の仕様を以下にメモします
特に何も問題ないようでしたら優先順位上がりましたしこちらの作業にとりかかりますね

* 「星の人気順」は「星の合計数」ではなく、動画につけられた全てのStarオブジェクト(ツクリガにおけるPointオブジェクトに該当)それぞれを1/2乗した値の合計を「動画ごとの星のポイント」(便宜上これ以降は星値と呼称する)として、それの高低をソートしたものである
* ただし、ツクリガのPointオブジェクトは期間ごとに別オブジェクトとなっているため、動画ごとの正確な星値の算出方法は以下としなければならない
1.  算出期間内(前日、週間、月間、全期間のいずれか)に動画につけられたPointオブジェクト全てを抽出
2. 1で抽出した配列からユーザーごとにPointオブジェクトをグループ分けする
3.  動画に対してつけられたユーザーごとのPointオブジェクトを全て合計し、1/2乗する(この値をユーザー星値とする)
4. ユーザー星値を全て合計した値が星値となる

あと、「星順」「人気順」だけしか載ってませんけども、以前搭載した「再生数順」「コメント人数順」についても個別に実装し、プルリクを送る際にはこのissueを対象に送るという形でいいんでしょうか？
