### ISSUE TITLE
ランキング機能実装(人気順)

### ISSUE THREAD

**Issue by Compeito** [Compeito/tsukuriga#38]
#34

**Comment by Hayakuchi0** [comment]
とりあえずプルリクを送る前に以前の仕様をここに記述します
#34 にはAltwugの頃と同じ仕様と記されていたので、プルリクを送る際にはそれに準拠します
問題があれば修正したいのでご意見いただければ幸いです
個人的には(お気に入り数×お気に入り数)を(10×お気に入り数×お気に入り数)にしてお気に入りの比重を増やしたいです

* Altwug時代における総合人気順(ツクリガにおける「人気順」)は、動画ごとにつけられた評価指標(コメント人数、お気に入り登録者数、#37 にて記述した星値、再生数)を元にポイントに換算した値(便宜上これ以降は「人気値」と呼称する)でソートしたものである
* 集計期間における動画ごとの人気値の算出方法は以下のとおりである
1. #37 で定義したとおりの星値を算出
2. 投稿日時が集計期間外なら0、集計期間内なら再生数そのままを再生数値とする。
3. 集計期間内に動画につけられたコメントのユーザー数(コメント人数)を算出
4. 集計期間内に動画につけられたお気に入り数を取得
5. ((再生数値+星値)×コメント人数)+((お気に入り数×お気に入り数))を人気値とする
* プルリクエスト送信時点で、#34 における期間ごとの再生数を表すオブジェクト(Viewオブジェクト)が作成されている場合、再生数値については集計期間内につけられたViewオブジェクトにおける再生数の合計とする。ただし集計期間が「全期間」の場合には動画ごとのviews_countの値も再生数値に加算する。
* プルリクエスト送信時点でViewオブジェクトが存在しない場合Altwugのときと同様の仕様とする

**Comment by Compeito** [comment]
長いので全部は読んでませんが人気順以外は特に計算式を通さずただ期間に基づいて集計した値で並べ替えてください。変更行はメソッド1つ、モデルの選択肢追加、makemigrationsで済むはずです、多分

余談ですが計算処理が大きくなりすぎるので人気順以外はいずれ削除するかもしれません。今ラベルの順番を計算するのに使ってますが集計に使えるメソッドがあることが分かったので個別のランキングの計算はせずに検索設定の1つとすることを検討しています
そういうわけなのでコメント順やらは実装しないでください。AltwugでもPV的にもあまり使われていなかった印象です

**Comment by Hayakuchi0** [comment]
わかりました
ではとりあえず「星順」は保留(というか検索機能の拡張にissueを変更？)として、先に人気順だけ実装してから他のランキングの作業にとりかかりますね

**Comment by Hayakuchi0** [comment]
このIssueに関わるプルリクエストについて、以下の2つの構成としたいのですが問題ないでしょうか?
それともまとめたほうがいいですかね?
1. browse/modelsのRankingに、上記の仕様でcalc_popular関数を追加(集計及びアドレス直打ちでのアクセスのみ行えるようにする)
2. フロント側でのランキングの表示に「人気順を追加」

**Comment by Hayakuchi0** [comment]
すいません
やる気が起きなかったので作業開始が送れてしまい、現在テストに思いの他時間かかってるので、間に合いませんでした
エラーが起きないことを確認した途中経過としてはこんな感じです
https://github.com/Hayakuchi0/tsukuriga/commit/c1f1b1fd2a03631e4ebe120649794583d93afc18

**Comment by Hayakuchi0** [comment]
以下の理由に基づき、星値、コメント人数、再生数値の算出は別メソッドに分割しました

* メソッド1つに50行もかけるのはやや重い
* テストコードを個別のメソッドごとに走らせるので不具合時に原因を特定しやすい
* 再生数値の算出は今後見直されるため確実に個別に修正が入るため

**Comment by Compeito** [comment]
メソッドの分割良いと思います。星がまだちょっと長いので匿名とユーザーに分けても良さそうです

**Comment by Hayakuchi0** [comment]
了解です
星を匿名とユーザーに分割しますね
各メソッドがどういう点数を返すのかはメソッドに対しdocstringをつけるということにしておきます
星値についてはややこしいので仕様を明記した#37 へリンクを貼るという形にしますが、ソース内に詳細に明記して欲しいとのことでしたら言ってください
test.pyと一緒に明日の23時を目標に、最悪でも明後日の23時にはプルリクおくります

**Comment by Compeito** [comment]
リンクは貼らずに、メソッドの説明はそれぞれ一行か多くても二行で収まる説明でお願いします。どうしても厳密な定義を箇条書しないといけないようであれば申し訳ないですがその実装は考え直して欲しいです

**Comment by Hayakuchi0** [comment]
了解です
とはいえ二行つかっていいのであればそこでおさまるので以下の2行で書きますね
```
動画に対してユーザーがつけた星の数をそれぞれ1/2乗し、全てのユーザーについてそれらを合計した値。
ただし集計期間外につけられた星は算出対象から除外する。
```

**Comment by Compeito** [comment]
良いと思います

**Comment by Hayakuchi0** [comment]
機能そのもののコードは前回の提出分からさほど量が変わってないのですが、機能分を除いたテストコードの行数が100行を超えました。
合計すると200行を超えそうな見通しです。
以下のように3つに分割してプルリクエストを送りたいですが、よろしいでしょうか？

1. 機能分のコード約60行(依存PRなし)
2. テストデータベース構築用のメソッド等のcore/utils.pyに入れられるレベルの汎用的なテストコード約80行(依存PRなし)
3. ランキング機能(人気順)のテストコード(1及び2に依存)

**Comment by Compeito** [comment]
コードがちゃんと見やすく書かれてるなら良いですが行数だけ見ると結構萎える数字です
Djangoのテストはデータベースが別で自動作成されるらしいですがまさかその辺自前で実装してたりします？Djangoがサポートしてるテストについてもう少し調べて、減らせるところは減らしてみてください

**Comment by Hayakuchi0** [comment]
2については「別で自動作成されるデータベース」にテスト対象のデータを登録する処理の簡略化というか自動化を行うメソッドですね
具体的にはobjects.createで何人もユーザー作ったり何十個もコメントやら星やらお気に入りやらを登録する作業を可能な限り自動化して行数を短縮するためのメソッドと、それに必要なメソッドを入れてます
fixtureで書くと200行(データ1つあたり5行を40個)くらいのjsonが必要になるところを80行(メソッド集)+40行(テストの際確認必須な部分のみを指定して残りは自動生成を1行で行う。それをデータ40個分)程度まで圧縮してます
読みやすいかに関していえばひとつの自動生成メソッドあたり最大でも11行という状況ですね

**Comment by Compeito** [comment]
あーそうかランキングだからユーザー作成と評価データの作成も含んでるんですね
んんんんんんとりあえずコード見てみないとなんとも言えないので、とりあえずPR出してみてください

**Comment by Hayakuchi0** [comment]
了解です〜
あとちょっとなので18時までには遅れそうです
ただ、すみませんがテスト項目が想像以上に多かったので3が100行をギリギリ超えそうです
事前にざっくりとしか計算してなくて申し訳なかったです
具体的には集計期間の種類数*(評価指標数-1+1)=16個、それに加えて星の集計は匿名とログインで分けてるので追加で2個のテストメソッドが必要でそれぞれが4行要るので72行、データ作成に40行程度食ってます

**Comment by Hayakuchi0** [comment]
とりあえず先に1と2だけ送っちゃいます

**Comment by Hayakuchi0** [comment]
3つのプルリクエストを全て送信しました
ご確認いただければ幸いです

**Comment by Compeito** [comment]
軽く見ただけですがテスト多すぎませんか？特にdayとかweekとかは`{期間: 期待する結果}`で辞書のリストやタプルのリストを作ればforで回せそうな雰囲気です。それにしても多いですが

**Comment by Hayakuchi0** [comment]
TestCaseのサブクラスはtestと名のつくメソッド全てを巡回するという形でテストを行うので、期間や評価指標ごとにforで回すとどこの期間やどの評価指標でエラーがおきたかがわからなくなるためこのような形となりました
また、仮にそれを無視してforで回すとAltwugの頃のranker.pyと似たような秘伝のソースが出来上がると思います

**Comment by Compeito** [comment]
ググったらテストは単体で理解できるのがいいらしいです。そういう意味ではDRY原則は適用されないとのこと

テストについてですが、ツクリガにおいてはコードの正確性を保証するものではなく、メソッドの使用例を記述する程度のものにしていきたいです。具体的には各期間まで回る必要はなくて各メソッド一回ずつするとか。そもそもutilsから段階的に実装していくという予定だったので、このプルリクにテストを入れたのは少し早かったですね

人気順部分は後でレビューします。他はクローズすると思います

**Comment by Hayakuchi0** [comment]
ありがとうございます
了解です

**Comment by Hayakuchi0** [comment]
マージありがとうございます
以下の3つの修正を加えたいです

Altwug時代の仕様の引き継ぎ漏れ2件

* score_of_commentsの計算結果を常時+1 (コメントがない作品も評価されるように、コメント人数+1になるようにする)
* score_of_viewの計算結果を1/2乗 (再生数は全員で星を1つづつつけたのと等価にする)

評価関数の修正

* 評価関数を((星+再生数値)×コメント人数)+(お気に入り×お気に入り)から、((星+再生数値)×コメント人数)+(お気に入り)へ変更

**Comment by Compeito** [comment]
良いと思います。プルリクお願いします
ここは閉じておくので、何かあれば新しく建てて下さい
