### ISSUE TITLE
星の荒らし対策について

### ISSUE THREAD

**Issue by Hayakuchi0** [Compeito/tsukuriga#44]
早急に必要というわけではないのですが、現在の星の仕様だとAltwug時代に搭載した星荒らし対策機能が抜けている&スクリプト爆撃にも脆弱っぽいので星荒らしの対策としてAltwug時代に実装していた連打時の待機時間について実装したほうがいいと思います
現在考えている仕様としては以下の形がいいと考えていますが、いかがでしょうか？
1. モーダルフォーム展開時に星を入れる旨をREST API経由でajax送信、それと同時に自分がつけた星の合計数を取得
2. 星を連打する際の待機時間を、(自分がつけた星の合計数+現在連打してる星の数)ミリ秒追加
3. 星を送信した際に、1で入れた時間からの経過時間を測定し、送信する星の数から2で発生するはずの待機時間の最低値を計算しそれ以下なら弾く、そうでないなら星の追加を通す。ただし、1で入れた時間からの経過時間が24時間以上であれば弾く

**Comment by Compeito** [comment]
対策が抜けているというか元々実装してません。星の連打による通信量についてはモーダル展開と送信を一回にすることでだいぶ対策になっていると思います。スクリプトとか組んでくるような真面目なやつは、もうどこを対策してもキリがないかなと思ってます。どちらかと言えばprojectsに載せた投稿やコメントの対策を優先します
星の評価価値については人気順の計算式を考えるときに調整します

**Comment by Hayakuchi0** [comment]
了解です
では杞憂だったということでcloseしますね
人気順といえば今実装の手始めとして再生数の集計案についてCommentを送ったのでご確認いただければ幸いです
