### ISSUE TITLE
関連動画的なもの

### ISSUE THREAD

**Issue by Compeito** [Compeito/tsukuriga#46]
* 動画ページの詳細情報(core/components/video-data.html)の下スペースに関連動画を載せる
  * とりあえずラベルが同じものからランダム(`.order_by('?')`)表示が簡単そう
  * ラベル未登録動画が少ないのははランキングか全体新着から持ってきてもいい
* せっかくPython使ってるしAIを使ってもいいけど面倒そう

**Comment by Hayakuchi0** [comment]
とりあえず「面倒なシステムはヤダ！」という方針ですとAIというか機械学習を使う想定はないほうがいいと思います
SVMやSCW等で線形分離することを想定してますが、ただの画像ファイルでさえ以下のような判別指標が必要なのに動画でやるとさらにフレームごとの差分や再生時間や音声の判別も必要になり、判別指標が多すぎて最低でもソースコードの1000行の追加はくだらないと思いますし、評価関数に用いる次元数も100はゆうに超えるはずです
・存在する物体や領域の数、種類
・領域及び物体ごとの複雑度、面積、明度、彩度、色相
・上記それぞれにおける中央値、平均値、最小値、最大値、最大値と最小値の差
また、学習用のモデルデータをどう用意するのか？どうラベルづけするのか？という課題も浮上し、やるにしても半年はかかるでしょう

**Comment by Compeito** [comment]
やるにしても閲覧履歴に基づく協調フィルタリングとかを考えてました
といっても調べるのがめんどいので多分やりません。書いてみただけです

**Comment by Hayakuchi0** [comment]
了解です
まずはラベルやハッシュタグが同じものからやることにしましょう
ラベルやハッシュタグがないものについては関連動画なしでいいかと…
実際ランキングや全体新着から持ってきたら本当に無関係の動画ですし…

ところで思ったんですが、関連動画が少ない時とかのあまった表示部分について、ユーザーが自分で関連動画を設定する機能を搭載するとかどうでしょうかね?
ニコニコ市場的な…
それならユーザーの新しい遊び場や宣伝にもなりますし、運営的には関連動画探す手間が省けます
Altwugの頃ののタグ機能の仕様を流用すればいいだけですし

**Comment by Compeito** [comment]
ええーまず関連動画を設定させるためのUIを作るのが大変そうですし、その割に誰も使わないと思います。めんどくさいので。使ったとしても自分の動画くらいしか貼らない(他人の動画は貼りづらい)と思うので、それなら無関係なのが表示された方がマシだと思います

**Comment by Hayakuchi0** [comment]
たしかに使うまでのハードル高かったら誰も使わないですね…
ではその仕様でいきましょうか
