### ISSUE TITLE
通報機能

### ISSUE THREAD

**Issue by Hayakuchi0** [Compeito/tsukuriga#50]
https://github.com/Compeito/tsukuriga/projects/3#card-19477468
で優先度[高]に割り振られていたので、プルリク送信の整理用にissueを作成しました
とりあえずは以下の仕様でプルリクを作成しますが、変えたい部分があったら言ってくださると幸いです

* APIについて、それなりに処理の記述量が多いのでajax/securityというappを作成し、そこでviewとurlを管理、アクセス先はPOST限定で/ajax/security/<slug:hotline_type>/<slug:target>。非ログインユーザーでは使えないことをエラーメッセージで明示するためlogin_requiredデコレータはなし。
* modelsについて、DBで保持するデータは以下とする。通報理由は通報者のハードルを上げる&理由かかれなきゃわからない程度のものを対処する必要がないので不要かと思ってたが、権利者による削除申請のような対応も通報機能でやる必要があるので必須と判断。
1. 通報者
2. 通報対象のタイプ(動画、コメント、ユーザー)
3. 通報対象
4. 通報理由
* フロント側の挙動について、星機能の要領で通報ボタンを作成し、モーダルフォームにて「通報しますか？」という確認を入れた後通報するというUIとする。
* 上記3つは独立して作成し、全てができたら結合を行う。

**Comment by Compeito** [comment]
通報機能は選択肢形式にして文章を自動生成してADMIN_MAILへ送る感じにしようと思ってます。返信もメールでそのまま出来ますし。そういうわけなのでモデルやビューの作成は不要だと考えてます

**Comment by Hayakuchi0** [comment]
了解です
そうなるとフロント側からajaxAPIを経由せずに直接ADMIN_MAILに送るという認識で大丈夫ですかね？
ajaxAPIを使うとなると結局viewは作ることになりますけども…

**Comment by Compeito** [comment]
ああビューは必要です。フロントではやりません

**Comment by Hayakuchi0** [comment]
わかりました
では以下の仕様で作って大丈夫でしょうか？

* securityアプリケーションは作成せず、ajax/views.py内でhotline関数を作成、ルーティングはajax/hotline
* 通報用のフォームを作成。(ajax/forms.pyにてHotLineFormを宣言、フォーム投稿には通報ボタン押下→モーダルフォームからの展開とする。)フォームの選択肢は以下の通り
1. 通報対象は動画ですか、ユーザーですか、コメントですか
2. 動画の場合、「動画のURLを記入してください」。ユーザーの場合「対象のユーザーIDを記入してください」。コメントの場合「コメントを記入したユーザー名と、コメントが記入された動画のURLを記入して下さい」
3. 通報理由を選択(選択肢は利用規約における禁止事項のどれに該当するかを選ぶ。権利者削除についてもここに入れる)
4. 「返信用のメールアドレスを記入して下さい」と返信用のメールアドレスを記入させる
* hotline関数内ではHotLineFormのデータを取得してADMIN_MAILに送信する処理を記述

**Comment by Compeito** [comment]
モーダルって結構作るのめんどいので単体ページのFormViewにするかもです
メールのテストとか環境用意するのも面倒でしょうし作るならこっちでやります。そういうのもあって優先度は下げました

**Comment by Hayakuchi0** [comment]
わかりました
では通報機能についてはよろしくお願いします
ちなみに#53 がcloseされたのはひょっとして同じ作業しててconflictしてしまったからということでいいんです？
理由考えてみたらProjectの「作業中」って「(contributerの誰かが)作業中」かと思ってましたけども「(Compeitoさんが)作業中」という意味な気がしてきたので…

**Comment by Compeito** [comment]
すみません通報関連をクローズしてたときにまとめてクローズしちゃいました
変更内容もよく分からないので見てても通してないと思います

**Comment by Hayakuchi0** [comment]
了解です
変更内容についてはこれから提出するcommitを以下のように複数に切り分けるために、全てにおいて事前に必要なModelだけ先に作った感じですね
* 再生数増加時にViewを作成、加算する処理
* 再生数表示時に表示させる値をViewも加算した際の処理
* 人気順集計の処理
commitを分割しようとすると#53みたいなcommitも増えると思いますけども、#47 ではなるべく切り分ける方針にはしたいですしどうしましょうか…

**Comment by Compeito** [comment]
1コミットにつきプルリクを出して欲しいわけではなく、意味単位で切り分けてほしいということです
詳しく読んだわけではないので僕の考えと完全に合致するわけではないですが、以下のような記事が参考になるかもしれないです
https://qiita.com/SpicyCoffee/items/b580afe3a86fabf61b1c
https://techracho.bpsinc.jp/hachi8833/2018_02_07/51095

**Comment by Compeito** [comment]
あとこういうコミットをmasterにマージしていくと細かいバグ修正などが出しにくくなる(UI開発中だと不完全なままリリースしてしまうとか)ので、`develop`ブランチを作りました。
その他貢献向けの資料を拡充していきたいので#54 を建てました。何かあれば意見下さい

**Comment by Hayakuchi0** [comment]
ありがとうございます
わかりました
そちらを参照しますね
