### ISSUE TITLE
貢献者向け環境整備

### ISSUE THREAD

**Issue by Compeito** [Compeito/tsukuriga#54]
* .githubディレクトリ、ISSUE_TEMPLATE.md、PULL_REQUEST_TEMPLATE.mdの作成
* コミットメッセージの命名規則を明確に

**Comment by Compeito** [comment]
developブランチ作成

**Comment by Hayakuchi0** [comment]
ISSUE_TEMPLATE等を作るにあたっては方針を決める必要があります
方針についての認識を合わせたいです
今までの話し合いについて、#50 にて記されたリンクを優先して整理すると以下のようになると解釈してます
とりあえずたたき台としてツッコみまくっていただければ幸いです

# 貢献者の条件について

貢献者は、以下の条件を満たす必要がある
この条件を満たしていない貢献者へのサポートは行わない方針とする

* 現状のREADMEのみを情報源として、clone,ビルド,fork,動作確認までが可能な技術力及び開発環境を保有
* ここで決まる開発規約を読み、実行する

# 新規機能について

貢献者が新規機能を作成する場合、以下の手順となる。
基本的にPRは手戻りして貢献者の負荷を高めたくない事、レビュー負荷を軽減したいことからウォーターフォール開発のように仕様は予め策定すること

1. Issue作成
2. 要件定義
3. 仕様策定
4. 必要なPRの一覧とPRごとの依存関係を策定(PRは意味単位で切り分ける。ひとつのPRのうち、変更は最大でも100行以内として粒度を切り分ける。100行を越えそうな場合切り分ける旨を報告する。)
5. developブランチにPR送信
6. Ownerがコードレビューを実施、developブランチにて動作確認。Ownerが承認しなければ手戻り
7. 全てのPRについてOwnerの承認が完了したらclose

# リファクタについて

新規機能とリファクタは別のIssueとして作成する。
新規機能がリファクタに依存する場合新規機能側にリファクタが依存することを明記すること

# テストについて

Djangoのテスト機能(test.py)は今までプルリクエストに含めなかったが、今後はテストをプルリクエストに含める。
ただしこれはレビュー負荷の軽減のためであり、テスト駆動開発を目的としたものではない。

# migrationについて

migrationファイルは従来通りプルリクエストに含まないものとする。

**Comment by Compeito** [comment]
えーとこれはCONTRIBUTING.mdとかに載せるようなやつってことでいいですかね。まず利用規約みたいな堅い文体で長々と書いても誰も読まないので、やってほしいこととやってほしくないことを箇条書きするに留めるつもりです

それを踏まえて気になったところですがまずマイグレーションファイルは普通にプルリクエストに入れてください。マイグレーションファイルをgitignoreすべきかどうかは検索するとスタックオーバーフローあたりないくらか出てくると思うのでその辺を読んでみてください

次にテストですが基本作らない方向ですが、ビューを除く自作した関数やクラスに段階的に実装していきたいなと考えてます。簡易的なテスト駆動開発、関数やメソッドの使用例の明示、ビュー関数が肥大化することを防ぐ(理想としては全部のビューが動画インポート処理のように書かれている)ことなどメリットが多いと思うからです。これは気が向いたら別でissueを建てるので気が向くのを待ってください

他は箇条書するにあたって参考にします。ありがとうございます

**Comment by Hayakuchi0** [comment]
迷走を防ぐためにフワフワした部分を可能な限り削いで堅苦しくきっちり開発方針を固めるとこうなるってやつですね
開発規約で引用元にしたりCONTRIBUTING.mdにそのままコピペしても大丈夫なようになってるとは思います
わかりました
ではAltwugの頃は弾くという話でしたがツクリガからは含めるということで把握です
テスト周りについて待ってます～
一応Issueが作られるまでは今までと同じように含めないでおきますね

**Comment by Compeito** [comment]
3ce77820b9ff41caac3156012dab9c70a4a896e3
