### ISSUE TITLE
連投対策(動画)

### ISSUE THREAD

**Issue by Hayakuchi0** [Compeito/tsukuriga#56]
優先順位が高いため、早めに作業に取り掛れるよう予め仕様を確定するためにIssueを立てました
個人的にはアカウント作成後24時間投稿できないという仕様は以下の問題があると考えています

* IDを事前に大量に作っておき、荒らしたい気分の日になったら一斉に爆撃という形で回避可能
* 普通に新しくサイトを見に来たまともなユーザーに対して初見バイバイすぎる

よって、以下の仕様を提案したいです

* アカウント作成を拒否したりなど、APIへのアクセスを制限する対象とその制限レベルを記録するIPアドレスの一覧をデータベースに作成(新規モデル)
* アカウント作成時にIPアドレスを記録
* 1週間ごとに一覧からIPを削除するというフラグを用意し、普段はアカウント作成直後のIPはTrueにする
* BAN対象はFalseとし、FalseのIPは定期削除の対象から外れて時効まで永久BAN

これなら前回Altwugに搭載した荒らし対策機能と同じくTor鯖を弾くことも可能ですし、良心的なユーザーの利便性を損なうこともありません

その上で、利用期間に応じて使用出来るリソース量(容量、動画数など)を決定するという機能(Altwugの頃うやむやになったACT機能)で、1日目のユーザーの投稿可能数を制限するという形をとれば大人数の荒らしに対してもある程度対策可能かと思われます
そもそものセキュリティレベルとしてスクリプト爆撃を想定してない程度なので組織的な攻撃は諦めてもいいのではという話もあるっちゃありますが…

**Comment by Hayakuchi0** [comment]
あともうひとつ思いついたのですが、登録して日が浅い人ほど公開動画になるまでの時間が長くなる仕様とかどうでしょうかね
「ふむ、このサイトええやん」→「登録して過去作投稿してやるぜー!」→「明日にならんと投稿できんよ」はやる気デストラクションですけども、登録直後の人の動画は公開までに時間がかかることが明記されてる程度であれば「明日の公開が楽しみだなー」で済む人もそれなりにいそうな気がしますし、次の日からはすぐに公開されることがわかってれば不便と感じる度合いはかなり軽減されそうかなと

**Comment by Compeito** [comment]
問題に関しては同意しますが、そこまでしなくてもいいかなーと思いました。あとissueが長いです
Torブロックは登録するIPアドレスが大量にあるのでadminからの登録は不向きかと思います。以下を参考にnginx側で対応します。
https://qiita.com/noraworld/items/c403ae1e63de9676dc03

**Comment by Compeito** [comment]
* Altwugみたいな15分制限を新規アカウント限定に適用
* 同一IPアドレスからのアカウント連続作成を抑制する何かしらの処理

とか

**Comment by Hayakuchi0** [comment]
Issue長いのはなんというかすみません…
了解です
前者は数値をもう少しキツくすればよさそうだと思います
後者についてはUserにIPAddresFieldを作って最終ログイン時のIPアドレスを記録して、それと同一のIPは最終ログインから3日以上の間は作成できないという仕様はどうでしょうか?

**Comment by Compeito** [comment]
とりあえず10分から始めますか
今日暇なのでまとめて実装しておきます
