### ISSUE TITLE
キーボード・ショートカットについて

### ISSUE THREAD

**Issue by Hayakuchi0** [Compeito/tsukuriga#62]
Altwugの頃のキーボード・ショートカットの仕様について、同様の仕様を再び採用する場合はvideoにtabIndexを付与し、focusしてる時のみキーボード・ショートカットを有効として欲しいです
理由としては以下のとおりです

* コメント入力(Altwugであればタグ入力も)時に左右キーを使用できないので推敲しづらい
* ブラウザ標準のキーボード・ショートカットが使用できない(特にUI上気になったのがブラウザバックのAlt+←が使用できない)

**Comment by Compeito** [comment]
とりあえず実装してみました
テキストエリアと同時入力系のキーを弾いてます
